### ISSUE TITLE
Wrong "alert-path" style command transformation

### ISSUE THREAD

**Issue by manweCZ** [SteffenBlake/PoeFilterX#8]
```
sound-extra-high-tier{
    alert-path: "REALLY_GOOD.mp3"; #result is same without question marks
}

```
compiles to 
`CustomAlertSound REALLY_GOOD.mp3` without question marks and PoE marks it as invalid

Expected behavior:
compile to `CustomAlertSound "REALLY_GOOD.mp3"`

**Comment by SteffenBlake** [comment]
Confirmed bugged in v3.19.3, opening this for fix and slating it for release v.3.22.0
